application: ward-directory
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /(submit|upload|jquery\.js|favicon\.ico)?
  login: required
  secure: always
  script: _go_app
