application: ward-directory
version: 1
runtime: go
api_version: go1

handlers:
- url: /site.css
  static_files: site.css
  upload: site.css
  secure: always

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /(submit|upload)?
  login: required
  secure: always
  script: _go_app
